name = "cloudflare-d1-worker"
main = ".open-next/worker.js"
compatibility_date = "2025-12-13"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "affiliate-database"
database_id = "af513c28-4e8a-40cd-83eb-7b1a03f7ba57"
migrations_dir = "./migrations"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "affiliate-cache"
[assets]
directory = ".open-next/assets"
binding = "ASSETS"