name = "affiliate-d1-admin"
main = "src/db/seeds/admin.worker.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "affiliate-database"
database_id = "38902e0c-e08c-461f-a1f7-a5a6f9d50ae2"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true