name = "tracking-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *", "0 0 * * *"]

# Production settings
# No [vars] needed here

[env.dev]
name = "tracking-worker-dev"
# No [vars] needed here
